### ISSUE TITLE
PandocBin TypeError in OSX 10.10.5, npm 3.8.6, node 6.0.0, pandoc-bin 0.1.2

### ISSUE THREAD

**Issue by gedkott** [toshgoodson/pandoc-bin#2]
I don't mind fixing this, but I need a tiny bit of pre-guidance:

npm info lifecycle pandoc-bin@0.1.2~postinstall: pandoc-bin@0.1.2

> pandoc-bin@0.1.2 postinstall .../node_modules/pandoc-bin
> node index.js

⧗ Downloading Pandoc (~20-50MB depending on OS). This may take a minute or so.
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received { url: 'https://raw.github.com/toshgoodson/pandoc-bin/0.1.0/vendor/osx/pandoc',
  name: 'pandoc',
  os: 'darwin' }
    at assertPath (path.js:7:11)
    at Object.basename (path.js:1355:5)
    at .../node_modules/download/index.js:35:43
    at each (.../node_modules/each-async/each-async.js:63:4)
    at module.exports (.../node_modules/download/index.js:33:5)
    at .../node_modules/bin-wrapper/index.js:108:20
    at .../node_modules/bin-wrapper/index.js:141:24
    at .../node_modules/bin-check/index.js:30:20
    at .../node_modules/executable/index.js:39:20

**Comment by juunas11** [comment]
+1 got this on Windows 10 also, same Pandoc-bin version

**Comment by tonywoode** [comment]
looks like pandoc-bin has to be installed globally, or you'll get that error!
